### ISSUE TITLE
Tornado mail tls: No appropriate protocol

### ISSUE THREAD

**Issue by ironbirdie** [Docmosis/tornado-docker#11]
Hi, We are using the docker image to deploy our tornado, but since the upgrade to 2.9.6, we are getting an issue to connect to our mailhost, it does work when disable mail-tls.

2023-08-24 13:23:09,741 [Docmosis-Mail-Transport-1] WARNING com.docmosis.web.service.common.destination.A - [localGateway] Failed to connect to mail gateway.  Will try this many more times:2
javax.mail.MessagingException: Can't send command to SMTP host;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1717)
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1704)
        at com.sun.mail.smtp.SMTPTransport.ehlo(SMTPTransport.java:1088)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:468)
        at javax.mail.Service.connect(Service.java:291)
        at javax.mail.Service.connect(Service.java:172)
        at javax.mail.Service.connect(Service.java:192)
        at com.docmosis.web.service.common.destination.A.A(line:301)
        at com.docmosis.web.service.common.destination.A.A(line:30)
        at com.docmosis.web.service.common.destination.A$2.A(line:121)
        at com.docmosis.web.service.common.destination.A$2.call(line:117)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
        at java.base/sun.security.ssl.HandshakeContext.<init>(HandshakeContext.java:170)
        at java.base/sun.security.ssl.ClientHandshakeContext.<init>(ClientHandshakeContext.java:103)
        at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:229)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:449)
        at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:926)
        at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1296)
        at com.sun.mail.util.TraceOutputStream.write(TraceOutputStream.java:110)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at com.sun.mail.smtp.SMTPTransport.sendCommand(SMTPTransport.java:1715)
        ... 14 more

**Comment by pauljowett** [comment]
Can you please raise this with support@docmosis.com?  Please include the version you were previously using and whether you have any changes to the Dockerfile.

**Comment by mikehhodgson** [comment]
Fixed in version 2.9.7, released Nov 2023.
